### ISSUE TITLE
Can't contribute to empty repository

### ISSUE THREAD

**Issue by thisisibrahimd** [ScoreTrak/helm-charts#1]
I am having trouble contributing to this repository because it is empty. I can't fork an empty to create a pull request, push to master branch, or create another branch on an empty repository.

Can you add a basic .gitignore so I can work from there?

**Comment by L1ghtman2k** [comment]
This is wired, as a member of org, you should be able to clone it... I just created gitignore, try to clone it

**Comment by thisisibrahimd** [comment]
Yeah weird. it works know, not sure how my setup changed in the past hour 🤷‍♂️. Thanks for the gitignore
